language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install -r requirements-dev.txt
script:
  - python -m pytest .
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWD
  distributions: "sdist"
  on:
    branch: master