language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install -r requirements-dev.txt

script:
  - python -m pytest .

deploy:
  distributions: "sdist bdist_wheel"
  skip_existing: true
  provider: pypi
  user: $PYPI_USER
  password:
    secure: $PYPI_SECURE
  on:
    tags: true
    branch: master
